# Basic Python script to collate quizes from sites using web scraping methods

In [101]:
#importing necessary packages 
import requests
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.options import Options
import time
import pandas as pd

In [32]:
#scraping quize from javapoint 
# Making a GET request
r = requests.get('https://engineeringinterviewquestions.com/dbms-multiple-choice-questions/')
# Parsing the HTML
soup = BeautifulSoup(r.content, 'html.parser')

In [45]:
# parsing the html tags from various classes
ques = []
for parent in soup.find_all('div',{'class':'entry-content'}):
    for tag in parent.find_all('p'):
        for x in tag.find_all('strong'):
            for q in x:
                ques.append(q.text)

In [46]:
ques

['1. In the relational model, cardinality is termed as:',
 'Answer: A',
 '2. Relational calculus is a',
 'Answer: B',
 '3. The view of total database content is',
 'Answer: A',
 '4. Cartesian product in relational algebra is',
 'Ans: B\xa0',
 '5. DML is provided for',
 'Answer: C',
 '6. \xa0‘AS’ clause is used in SQL for',
 'Answer: B',
 '7. \xa0ODBC stands for',
 'Answer: D',
 '8 Architecture of the database can be viewed as',
 'Answer: C',
 '9 In a relational model, relations are termed as',
 'Answer: C',
 '10 The database schema is written in',
 'Answer: C',
 '11 In the architecture of a database system external level is the',
 'Answer: D',
 '12 An entity set that does not have sufficient attributes to form a primary key is a',
 'Answer: B',
 '13 In Hierarchical model records are organised as',
 'Answer: D',
 '14 In an E-R diagram attributes are represented by',
 'Answer: C',
 '15 In case of entity integrity, the primary key maybe',
 'Answer: A',
 '16 In tuple relational calculus P1 ®P2 is equivalent to',
 'Answer: A',
 '17 The language used in application programs to request data from the DBMS is referred to as the',
 'Answer: A',
 '18 A logical schema',
 'Answer: A',
 '19 Related fields in a database are grouped to form a',
 'Answer: B',
 '20 The database environment has all of the following components except:',
 'Ans: A.',
 '21 The language which has recently become the defacto standard for interfacing application programs with relational database system is',
 'Answer: B',
 '22 The way a particular application views the data from the database that the application uses is a',
 'Answer: D',
 '23 In an E-R diagram an entity set is represented by a',
 'Answer: A',
 '24 A report generator is used to',
 'Answer: B',
 '25 The property/properties of a database is/are:',
 'Answer: D',
 '26 The DBMS language component which can be embedded in a program is',
 'Answer: B',
 '27 A relational database developer refers to a record as',
 'Answer: C',
 '28 The relational model feature is that there',
 'Answer: B',
 '29 Conceptual design',
 'Answer: C',
 '30 The method in which records are physically stored in a specified order according to a key field in each record is',
 'Answer: A',
 '31 A subschema expresses',
 'Answer: C',
 '32 Count function in SQL returns the number of',
 'Answer: A',
 '33 Which one of the following statements is false?',
 'Answer: B',
 '34 An advantage of the database management approach is',
 'Answer: C',
 '35 A DBMS query language is designed to',
 'Answer: D',
 '36 Transaction processing is associated with everything below except',
 'Answer: C',
 '37 It is possible to define a schema completely using',
 'Answer: B',
 '38 The method of access which uses key transformation is known as',
 'Answer: B',
 '39 Data independence me Ans',
 'Ans: D both B. and C.',
 '40 The statement in SQL which allows changing the definition of a table is',
 'Ans: A.',
 '41 E-R model uses this symbol to represent a weak entity set?',
 'Answer: C',
 '42 SET concept is used in:',
 'Answer: A',
 '43 Relational Algebra is',
 'Answer: C',
 '44 Key to represent the relationship between tables is called',
 'Answer: C',
 '45 _______ produces the relation that has attributes of R1 and R2',
 'Answer: A',
 '46 The file organisation that provides very fast access to any arbitrary record of a file is',
 'Answer: C',
 '47 DBMS helps achieve',
 'Answer: D',
 '48 Which of the following are the properties of entities?',
 'Answer: C',
 '49 In a relation',
 'Answer: C',
 '50 Which of the following is correct:',
 'Answer: D',
 '51 It is better to use files than a DBMS when there are',
 'Answer: B',
 '52 The conceptual model is',
 'Answer: D',
 '53 What is a relationship called when it is maintained between two entities?',
 'Answer: B',
 '54 Which of the following operation is used if we are interested in only certain columns of a table?',
 'Answer: A',
 '55 Which of the following is a valid SQL type?',
 'Answer: D',
 '56 The RDBMS terminology for a row is',
 'Answer: A',
 '57 Which of the following operations need the participating relations to be union compatible?',
 'Answer: D',
 '58 The full form of DDL is',
 'Answer: C',
 '59 Which of the following is an advantage of view?',
 'Answer: D',
 '60 Which of the following is a legal expression in SQL?',
 'Answer: B',
 '61 The users who use the easy-to-use menu are called',
 'Answer: B',
 '62 Which database level is closest to the users?',
 'Answer: A',
 '63 Which are the two ways in which entities can participate in a relationship?',
 'Answer: B',
 '64 The result of the UNION operation between R1 and R2 is a relation that includes',
 'Answer: D',
 '65 Which of the following is a comparison operator in SQL?',
 'Answer: D',
 '66 A set of possible data values is called',
 'Answer: D',
 '67 Which of the operations constitute a basic set of operations for manipulating relational data?',
 'Ans:C',
 '68 Which of the following is another name for the weak entity?',
 'Answer: A',
 '69 Which of the following database object does not physically exist?',
 'Answer: C',
 '70 NULL is',
 'Answer: D',
 '71 Which of the following is a record based logical model?',
 'Answer: A',
 '72 A data dictionary is a special file that contains:',
 'Answer: D',
 '73 A file manipulation command that extracts some of the records from a file is called',
 'Answer: A',
 '74 The physical location of a record is determined by a mathematical formula that transforms a file key into a record location is:',
 'Answer: B',
 '75 Using Relational Algebra the query that finds customers, who have a balance of over 1000 is',
 'Answer: A',
 '76 A primary key is combined with a foreign key creates',
 'Answer: A',
 '77 In E-R Diagram derived attribute is represented by',
 'Answer: B',
 '78 Cross Product is a:',
 'Answer: C',
 '79 An instance of relational schema R (A, B, C) has distinct values of A, including NULL values. Which one of the following is true?',
 'Answer: B',
 '80 Consider the join of a relation R with relation S. If R has m tuples and S has n tuples, then the maximum size of join is:',
 'Ans: A.',
 '81 The natural join is equal to:',
 'Answer: D',
 '82 Which one of the following is not true for a view:',
 'Answer: C',
 '83 A primary key, if combined with a foreign key, creates',
 'Answer: A',
 '84 In E-R Diagram relationship type is represented by',
 'Answer: D',
 '85 Hierarchical model is also called',
 'Answer: A',
 '86 To delete a particular column in a relation the command used is:',
 'Answer: C',
 '87 The ______ operator is used to compare a value to a list of literals values that have been specified.',
 'Answer: A',
 '88 A logical schema',
 'Answer: A',
 '89 A B-tree of order m has maximum of _____________ children',
 'Answer: A',
 '90 _____________ function divides one numeric expression by another and returns the remainder.',
 'Answer: B',
 '91 A data manipulation command the combines the records from one or more tables is called',
 'Answer: C',
 '92 In E-R diagram generalisation is represented by',
 'Answer: D',
 '93 _________ is a virtual table that draws its data from the result of an SQL SELECT statement.',
 'Answer: A',
 '94 The method of access which uses key transformation is known as',
 'Answer: B',
 '95 A table joined with itself is called',
 'Answer: B',
 '96 _________ data type can store unstructured data',
 'Answer: A']

In [120]:
q = []
q.append(ques[::2])

In [121]:
q

[['1. In the relational model, cardinality is termed as:',
  '2. Relational calculus is a',
  '3. The view of total database content is',
  '4. Cartesian product in relational algebra is',
  '5. DML is provided for',
  '6. \xa0‘AS’ clause is used in SQL for',
  '7. \xa0ODBC stands for',
  '8 Architecture of the database can be viewed as',
  '9 In a relational model, relations are termed as',
  '10 The database schema is written in',
  '11 In the architecture of a database system external level is the',
  '12 An entity set that does not have sufficient attributes to form a primary key is a',
  '13 In Hierarchical model records are organised as',
  '14 In an E-R diagram attributes are represented by',
  '15 In case of entity integrity, the primary key maybe',
  '16 In tuple relational calculus P1 ®P2 is equivalent to',
  '17 The language used in application programs to request data from the DBMS is referred to as the',
  '18 A logical schema',
  '19 Related fields in a database are grouped to form a',
  '20 The database environment has all of the following components except:',
  '21 The language which has recently become the defacto standard for interfacing application programs with relational database system is',
  '22 The way a particular application views the data from the database that the application uses is a',
  '23 In an E-R diagram an entity set is represented by a',
  '24 A report generator is used to',
  '25 The property/properties of a database is/are:',
  '26 The DBMS language component which can be embedded in a program is',
  '27 A relational database developer refers to a record as',
  '28 The relational model feature is that there',
  '29 Conceptual design',
  '30 The method in which records are physically stored in a specified order according to a key field in each record is',
  '31 A subschema expresses',
  '32 Count function in SQL returns the number of',
  '33 Which one of the following statements is false?',
  '34 An advantage of the database management approach is',
  '35 A DBMS query language is designed to',
  '36 Transaction processing is associated with everything below except',
  '37 It is possible to define a schema completely using',
  '38 The method of access which uses key transformation is known as',
  '39 Data independence me Ans',
  '40 The statement in SQL which allows changing the definition of a table is',
  '41 E-R model uses this symbol to represent a weak entity set?',
  '42 SET concept is used in:',
  '43 Relational Algebra is',
  '44 Key to represent the relationship between tables is called',
  '45 _______ produces the relation that has attributes of R1 and R2',
  '46 The file organisation that provides very fast access to any arbitrary record of a file is',
  '47 DBMS helps achieve',
  '48 Which of the following are the properties of entities?',
  '49 In a relation',
  '50 Which of the following is correct:',
  '51 It is better to use files than a DBMS when there are',
  '52 The conceptual model is',
  '53 What is a relationship called when it is maintained between two entities?',
  '54 Which of the following operation is used if we are interested in only certain columns of a table?',
  '55 Which of the following is a valid SQL type?',
  '56 The RDBMS terminology for a row is',
  '57 Which of the following operations need the participating relations to be union compatible?',
  '58 The full form of DDL is',
  '59 Which of the following is an advantage of view?',
  '60 Which of the following is a legal expression in SQL?',
  '61 The users who use the easy-to-use menu are called',
  '62 Which database level is closest to the users?',
  '63 Which are the two ways in which entities can participate in a relationship?',
  '64 The result of the UNION operation between R1 and R2 is a relation that includes',
  '65 Which of the following is a comparison operator in SQL?',
  '66 A set of possible data values is called',
  '67 Which of the operations constitute a basic set of operations for manipulating relational data?',
  '68 Which of the following is another name for the weak entity?',
  '69 Which of the following database object does not physically exist?',
  '70 NULL is',
  '71 Which of the following is a record based logical model?',
  '72 A data dictionary is a special file that contains:',
  '73 A file manipulation command that extracts some of the records from a file is called',
  '74 The physical location of a record is determined by a mathematical formula that transforms a file key into a record location is:',
  '75 Using Relational Algebra the query that finds customers, who have a balance of over 1000 is',
  '76 A primary key is combined with a foreign key creates',
  '77 In E-R Diagram derived attribute is represented by',
  '78 Cross Product is a:',
  '79 An instance of relational schema R (A, B, C) has distinct values of A, including NULL values. Which one of the following is true?',
  '80 Consider the join of a relation R with relation S. If R has m tuples and S has n tuples, then the maximum size of join is:',
  '81 The natural join is equal to:',
  '82 Which one of the following is not true for a view:',
  '83 A primary key, if combined with a foreign key, creates',
  '84 In E-R Diagram relationship type is represented by',
  '85 Hierarchical model is also called',
  '86 To delete a particular column in a relation the command used is:',
  '87 The ______ operator is used to compare a value to a list of literals values that have been specified.',
  '88 A logical schema',
  '89 A B-tree of order m has maximum of _____________ children',
  '90 _____________ function divides one numeric expression by another and returns the remainder.',
  '91 A data manipulation command the combines the records from one or more tables is called',
  '92 In E-R diagram generalisation is represented by',
  '93 _________ is a virtual table that draws its data from the result of an SQL SELECT statement.',
  '94 The method of access which uses key transformation is known as',
  '95 A table joined with itself is called',
  '96 _________ data type can store unstructured data']]

In [50]:
a = []
a.append(ques[1::2])

In [122]:
#function to flatten the nested list into a separate list 
qs = []
def reemovNestings(q):
    for i in q:
        if type(i) == list:
            reemovNestings(i)
        else:
            qs.append(i)
  
# Driver code
#print ('The original list: ', a)
reemovNestings(q)
print ('The list after removing nesting: ', qs)

The list after removing nesting:  ['1. In the relational model, cardinality is termed as:', '2. Relational calculus is a', '3. The view of total database content is', '4. Cartesian product in relational algebra is', '5. DML is provided for', '6. \xa0‘AS’ clause is used in SQL for', '7. \xa0ODBC stands for', '8 Architecture of the database can be viewed as', '9 In a relational model, relations are termed as', '10 The database schema is written in', '11 In the architecture of a database system external level is the', '12 An entity set that does not have sufficient attributes to form a primary key is a', '13 In Hierarchical model records are organised as', '14 In an E-R diagram attributes are represented by', '15 In case of entity integrity, the primary key maybe', '16 In tuple relational calculus P1 ®P2 is equivalent to', '17 The language used in application programs to request data from the DBMS is referred to as the', '18 A logical schema', '19 Related fields in a database are grouped to form a', '20 The database environment has all of the following components except:', '21 The language which has recently become the defacto standard for interfacing application programs with relational database system is', '22 The way a particular application views the data from the database that the application uses is a', '23 In an E-R diagram an entity set is represented by a', '24 A report generator is used to', '25 The property/properties of a database is/are:', '26 The DBMS language component which can be embedded in a program is', '27 A relational database developer refers to a record as', '28 The relational model feature is that there', '29 Conceptual design', '30 The method in which records are physically stored in a specified order according to a key field in each record is', '31 A subschema expresses', '32 Count function in SQL returns the number of', '33 Which one of the following statements is false?', '34 An advantage of the database management approach is', '35 A DBMS query language is designed to', '36 Transaction processing is associated with everything below except', '37 It is possible to define a schema completely using', '38 The method of access which uses key transformation is known as', '39 Data independence me Ans', '40 The statement in SQL which allows changing the definition of a table is', '41 E-R model uses this symbol to represent a weak entity set?', '42 SET concept is used in:', '43 Relational Algebra is', '44 Key to represent the relationship between tables is called', '45 _______ produces the relation that has attributes of R1 and R2', '46 The file organisation that provides very fast access to any arbitrary record of a file is', '47 DBMS helps achieve', '48 Which of the following are the properties of entities?', '49 In a relation', '50 Which of the following is correct:', '51 It is better to use files than a DBMS when there are', '52 The conceptual model is', '53 What is a relationship called when it is maintained between two entities?', '54 Which of the following operation is used if we are interested in only certain columns of a table?', '55 Which of the following is a valid SQL type?', '56 The RDBMS terminology for a row is', '57 Which of the following operations need the participating relations to be union compatible?', '58 The full form of DDL is', '59 Which of the following is an advantage of view?', '60 Which of the following is a legal expression in SQL?', '61 The users who use the easy-to-use menu are called', '62 Which database level is closest to the users?', '63 Which are the two ways in which entities can participate in a relationship?', '64 The result of the UNION operation between R1 and R2 is a relation that includes', '65 Which of the following is a comparison operator in SQL?', '66 A set of possible data values is called', '67 Which of the operations constitute a basic set of operations for manipulating relational data?', '68 Which of the following is another name for the weak entity?', '69 Which of the following database object does not physically exist?', '70 NULL is', '71 Which of the following is a record based logical model?', '72 A data dictionary is a special file that contains:', '73 A file manipulation command that extracts some of the records from a file is called', '74 The physical location of a record is determined by a mathematical formula that transforms a file key into a record location is:', '75 Using Relational Algebra the query that finds customers, who have a balance of over 1000 is', '76 A primary key is combined with a foreign key creates', '77 In E-R Diagram derived attribute is represented by', '78 Cross Product is a:', '79 An instance of relational schema R (A, B, C) has distinct values of A, including NULL values. Which one of the following is true?', '80 Consider the join of a relation R with relation S. If R has m tuples and S has n tuples, then the maximum size of join is:', '81 The natural join is equal to:', '82 Which one of the following is not true for a view:', '83 A primary key, if combined with a foreign key, creates', '84 In E-R Diagram relationship type is represented by', '85 Hierarchical model is also called', '86 To delete a particular column in a relation the command used is:', '87 The ______ operator is used to compare a value to a list of literals values that have been specified.', '88 A logical schema', '89 A B-tree of order m has maximum of _____________ children', '90 _____________ function divides one numeric expression by another and returns the remainder.', '91 A data manipulation command the combines the records from one or more tables is called', '92 In E-R diagram generalisation is represented by', '93 _________ is a virtual table that draws its data from the result of an SQL SELECT statement.', '94 The method of access which uses key transformation is known as', '95 A table joined with itself is called', '96 _________ data type can store unstructured data']

In [71]:
# parsing the html tags from various classes
options = []
for parent in soup.find_all('div',{'class':'entry-content'}):
    for tag in parent.find_all('p'):
        #print(tag)
        for q in tag:
            options.append(q.text)

In [72]:
options

['DBMS multiple choice questions and answers PDF for freshers and experienced',
 '1. In the relational model, cardinality is termed as:',
 'A. A number of tuples.',
 '',
 '\nB. A number of attributes.',
 '',
 '\nC. A number of tables.',
 '',
 '\nD. A number of constraints.',
 'Answer: A',
 '2. Relational calculus is a',
 'A. Procedural language.',
 '',
 '\nB. Non- Procedural language.',
 '',
 '\nC. Data definition language.',
 '',
 '\nD. High-level language.',
 'Answer: B',
 '3. The view of total database content is',
 'A. Conceptual view.',
 '',
 '\nB. Internal view.',
 '',
 '\nC. External view.',
 '',
 '\nD. Physical View.',
 'Answer: A',
 '4. Cartesian product in relational algebra is',
 'A. a Unary operator.',
 '',
 '\nB. a Binary operator.',
 '',
 '\nC. a Ternary operator.',
 '',
 '\nD. not defined.',
 'Ans: B\xa0',
 '5. DML is provided for',
 'A. Description of the logical structure of a database.',
 '',
 '\nB. The addition of new structures in the database system.',
 '',
 '\nC. Manipulation & processing of the database.',
 '',
 '\nD. Definition of a physical structure of the database system.',
 'Answer: C',
 '6. \xa0‘AS’ clause is used in SQL for',
 'A. Selection operation.',
 '',
 '\nB. Rename operation.',
 '',
 '\nC. Join operation.',
 '',
 '\nD. Projection operation.',
 'Answer: B',
 '7. \xa0ODBC stands for',
 'A. Object Database Connectivity.',
 '',
 '\nB. Oral Database Connectivity.',
 '',
 '\nC. Oracle Database Connectivity.',
 '',
 '\nD. Open Database Connectivity.',
 'Answer: D',
 '8 Architecture of the database can be viewed as',
 'A. two levels.',
 '',
 '\nB. four levels.',
 '',
 '\nC. three levels.',
 '',
 '\nD. one level.',
 'Answer: C',
 '9 In a relational model, relations are termed as',
 'A. Tuples.',
 '',
 '\nB. Attributes',
 '',
 '\nC. Tables.',
 '',
 '\nD. Rows.',
 'Answer: C',
 '10 The database schema is written in',
 'A. HLL',
 '',
 '\nB. DML',
 '',
 '\nC. DDL',
 '',
 '\nD. DCL',
 'Answer: C',
 '11 In the architecture of a database system external level is the',
 'A. physical level.',
 '',
 '\nB. logical level.',
 '',
 '\nC. conceptual level',
 '',
 '\nD. view level.',
 'Answer: D',
 '12 An entity set that does not have sufficient attributes to form a primary key is a',
 'A. strong entity set.',
 '',
 '\nB. weak entity set.',
 '',
 '\nC. simple entity set.',
 '',
 '\nD. primary entity set.',
 'Answer: B',
 '13 In Hierarchical model records are organised as',
 'A. Graph.',
 '',
 '\nB. List.',
 '',
 '\nC. Links.',
 '',
 '\nD. Tree.',
 'Answer: D',
 '14 In an E-R diagram attributes are represented by',
 'A. rectangle.',
 '',
 '\nB. square.',
 '',
 '\nC. ellipse.',
 '',
 '\nD. triangle.',
 'Answer: C',
 '15 In case of entity integrity, the primary key maybe',
 'A. not Null',
 '',
 '\nB. Null',
 '',
 '\nC. both Null & not Null.',
 '',
 '\nD. any value.',
 'Answer: A',
 '16 In tuple relational calculus P1 ®P2 is equivalent to',
 'A. ¬P1 Ú P2',
 '',
 '\nB. P1 Ú P2',
 '',
 '\nC. P1 Ù P2',
 '',
 '\nD. P1 Ù¬P2',
 'Answer: A',
 '17 The language used in application programs to request data from the DBMS is referred to as the',
 'A. DML',
 '',
 '\nB. DDL',
 '',
 '\nC. VDL',
 '',
 '\nD. SDL',
 'Answer: A',
 '18 A logical schema',
 'A. is the entire database.',
 '',
 '\nB. is a standard way of organising information into accessible parts.',
 '',
 '\nC. describes how data is actually stored on disk.',
 '',
 '\nD. both A. and C.',
 'Answer: A',
 '19 Related fields in a database are grouped to form a',
 'A. data file.',
 '',
 '\nB. data record.',
 '',
 '\nC. menu.',
 '',
 '\nD. bank.',
 'Answer: B',
 '20 The database environment has all of the following components except:',
 'A. users.',
 '',
 '\nB. separate files.',
 '',
 '\nC. database.',
 '',
 '\nD. database administrator.',
 'Ans: A.',
 '21 The language which has recently become the defacto standard for interfacing application programs with relational database system is',
 'A. Oracle.',
 '',
 '\nB. SQL.',
 '',
 '\nC. DBase.',
 '',
 '\nD. 4GL.',
 'Answer: B',
 '22 The way a particular application views the data from the database that the application uses is a',
 'A. module.',
 '',
 '\nB. relational model.',
 '',
 '\nC. schema.',
 '',
 '\nD. subschema.',
 'Answer: D',
 '23 In an E-R diagram an entity set is represented by a',
 'A. rectangle.',
 '',
 '\nB. ellipse.',
 '',
 '\nC. diamond box.',
 '',
 '\nD. circle.',
 'Answer: A',
 '24 A report generator is used to',
 'A. update files.',
 '',
 '\nB. print files on paper.',
 '',
 '\nC. data entry.',
 '',
 '\nD. delete files.',
 'Answer: B',
 '25 The property/properties of a database is/are:',
 'A. It is an integrated collection of logically related records.',
 '',
 '\nB. It consolidates separate files into a common pool of data records.',
 '',
 '\nC. Data stored in a database is independent of the application programs using it.',
 '',
 '\nD. All of the above.',
 'Answer: D',
 '26 The DBMS language component which can be embedded in a program is',
 'A. The data definition language (DDL).',
 '',
 '\nB. The data manipulation language (DML).',
 '',
 '\nC. The database administrator (DBA).',
 '',
 '\nD. A query language.',
 'Answer: B',
 '27 A relational database developer refers to a record as',
 'A. Criteria.',
 '',
 '\nB. a relation.',
 '',
 '\nC. a tuple.',
 '',
 '\nD. an attribute.',
 'Answer: C',
 '28 The relational model feature is that there',
 'A. is no need for primary key data.',
 '',
 '\nB. is much more data independence than some other database models.',
 '',
 '\nC. are explicit relationships among records.',
 '',
 '\nD. are tables with many dimensions.',
 'Answer: B',
 '29 Conceptual design',
 'A. is a documentation technique.',
 '',
 '\nB. needs data volume and processing frequencies to determine the size of the database.',
 '',
 '\nC. involves modelling independent of the DBMS.',
 '',
 '\nD. is designing the relational model.',
 'Answer: C',
 '30 The method in which records are physically stored in a specified order according to a key field in each record is',
 'A. hash.',
 '',
 '\nB. direct.',
 '',
 '\nC. sequential.',
 '',
 '\nD. all of the above.',
 'Answer: A',
 '31 A subschema expresses',
 'A. the logical view.',
 '',
 '\nB. the physical view.',
 '',
 '\nC. the external view.',
 '',
 '\nD. all of the above.',
 'Answer: C',
 '32 Count function in SQL returns the number of',
 'A. values.',
 '',
 '\nB. distinct values.',
 '',
 '\nC. groups.',
 '',
 '\nD. columns.',
 'Answer: A',
 '33 Which one of the following statements is false?',
 'A. The data dictionary is normally maintained by the database administrator.',
 '',
 '\nB. Data elements in the database can be modified by changing the data dictionary.',
 '',
 '\nC. The data dictionary contains the name and description of each data element.',
 '',
 '\nD. A data dictionary is a tool used exclusively by the database administrator.',
 'Answer: B',
 '34 An advantage of the database management approach is',
 'A. data is dependent on programs.',
 '',
 '\nB. data redundancy increases.',
 '',
 '\nC. data is integrated and can be accessed by multiple programs.',
 '',
 '\nD. none of the above.',
 'Answer: C',
 '35 A DBMS query language is designed to',
 'A. support end-users who use English-like commands.',
 '',
 '\nB. support in the development of complex applications software.',
 '',
 '\nC. specify the structure of a database.',
 '',
 '\nD. all of the above.',
 'Answer: D',
 '36 Transaction processing is associated with everything below except',
 'A. producing detail, summary, or exception reports.',
 '',
 '\nB. recording a business activity.',
 '',
 '\nC. confirming an action or triggering a response.',
 '',
 '\nD. maintaining data.',
 'Answer: C',
 '37 It is possible to define a schema completely using',
 'A. VDL and DDL.',
 '',
 '\nB. DDL and DML.',
 '',
 '\nC. SDL and DDL.',
 '',
 '\nD. VDL and DML.',
 'Answer: B',
 '38 The method of access which uses key transformation is known as',
 'A. direct.',
 '',
 '\nB. hash.',
 '',
 '\nC. random.',
 '',
 '\nD. sequential.',
 'Answer: B',
 '39 Data independence me Ans',
 'A. data is defined separately and not included in programs.',
 '',
 '\nB. programs are not dependent on the physical attributes of data.',
 '',
 '\nC. programs are not dependent on the logical attributes of data.',
 '',
 '\nD. both B. and C..',
 'Ans: D both B. and C.',
 '40 The statement in SQL which allows changing the definition of a table is',
 'A. Alter.',
 '',
 '\nB. Update.',
 '',
 '\nC. Create.',
 '',
 '\nD. select.',
 'Ans: A.',
 '41 E-R model uses this symbol to represent a weak entity set?',
 'A. Dotted rectangle.',
 '',
 '\nB. Diamond',
 '',
 '\nC. Doubly outlined rectangle',
 '',
 '\nD. None of these',
 'Answer: C',
 '42 SET concept is used in:',
 'A. Network Model',
 '',
 '\nB. Hierarchical Model',
 '',
 '\nC. Relational Model',
 '',
 '\nD. None of these',
 'Answer: A',
 '43 Relational Algebra is',
 'A. Data Definition Language.',
 '',
 '\nB. Meta Language',
 '',
 '\nC. Procedural Query Language',
 '',
 '\nD. None of the above',
 'Answer: C',
 '44 Key to represent the relationship between tables is called',
 'A. Primary key',
 '',
 '\nB. Secondary Key',
 '',
 '\nC. Foreign Key',
 '',
 '\nD. None of these',
 'Answer: C',
 '45 _______ produces the relation that has attributes of R1 and R2',
 'A. Cartesian product',
 '',
 '\nB. Difference',
 '',
 '\nC. Intersection',
 '',
 '\nD. Product',
 'Answer: A',
 '46 The file organisation that provides very fast access to any arbitrary record of a file is',
 'A. Ordered file',
 '',
 '\nB. Unordered file',
 '',
 '\nC. Hashed file',
 '',
 '\nD. B-tree',
 'Answer: C',
 '47 DBMS helps achieve',
 'A. Data independence',
 '',
 '\nB. Centralised control of data',
 '',
 '\nC. Neither A. or B.',
 '',
 '\nD. both A. and B.',
 'Answer: D',
 '48 Which of the following are the properties of entities?',
 'A. Groups',
 '',
 '\nB. Table',
 '',
 '\nC. Attributes',
 '',
 '\nD. Switchboards',
 'Answer: C',
 '49 In a relation',
 'A. Ordering of rows is immaterial',
 '',
 '\nB. No two rows are identical',
 '',
 '\nC. A. and B. both are true',
 '',
 '\nD. None of these.',
 'Answer: C',
 '50 Which of the following is correct:',
 'A. a SQL query automatically eliminates duplicates.',
 '',
 '\nB. SQL permits attribute names to be repeated in the same relation.',
 '',
 '\nC. a SQL query will not work if there are no indexes on the relations',
 '',
 '\nD. None of these',
 'Answer: D',
 '51 It is better to use files than a DBMS when there are',
 'A. Stringent real-time requirements.',
 '',
 '\nB. Multiple users wish to access the data.',
 '',
 '\nC. Complex relationships among data.',
 '',
 '\nD. All of the above.',
 'Answer: B',
 '52 The conceptual model is',
 'A. dependent on hardware.',
 '',
 '\nB. dependent on software.',
 '',
 '\nC. dependent on both hardware and software.',
 '',
 '\nD. independent of both hardware and software.',
 'Answer: D',
 '53 What is a relationship called when it is maintained between two entities?',
 'A. Unary',
 '',
 '\nB. Binary',
 '',
 '\nC. Ternary',
 '',
 '\nD. Quaternary',
 'Answer: B',
 '54 Which of the following operation is used if we are interested in only certain columns of a table?',
 'A. PROJECTION',
 '',
 '\nB. SELECTION',
 '',
 '\nC. UNION',
 '',
 '\nD. JOIN',
 'Answer: A',
 '55 Which of the following is a valid SQL type?',
 'A. CHARACTER',
 '',
 '\nB. NUMERIC',
 '',
 '\nC. FLOAT',
 '',
 '\nD. All of the above',
 'Answer: D',
 '56 The RDBMS terminology for a row is',
 'A. tuple.',
 '',
 '\nB. relation.',
 '',
 '\nC. attribute.',
 '',
 '\nD. degree.',
 'Answer: A',
 '57 Which of the following operations need the participating relations to be union compatible?',
 'A. UNION',
 '',
 '\nB. INTERSECTION',
 '',
 '\nC. DIFFERENCE',
 '',
 '\nD. All of the above',
 'Answer: D',
 '58 The full form of DDL is',
 '(A Dynamic Data Language',
 '',
 '\nB. Detailed Data Language',
 '',
 '\nC. Data Definition Language',
 '',
 '\nD. Data Derivation Language',
 'Answer: C',
 '59 Which of the following is an advantage of view?',
 'A. Data security',
 '',
 '\nB. Derived columns',
 '',
 '\nC. Hiding of complex queries',
 '',
 '\nD. All of the above',
 'Answer: D',
 '60 Which of the following is a legal expression in SQL?',
 'A. SELECT NULL FROM EMPLOYEE;',
 '',
 '\nB. SELECT NAME FROM EMPLOYEE;',
 '',
 '\nC. SELECT NAME FROM EMPLOYEE WHERE SALARY = NULL;',
 '',
 '\nD. None of the above',
 'Answer: B',
 '61 The users who use the easy-to-use menu are called',
 'A. Sophisticated end users.',
 '',
 '\nB. Naïve users.',
 '',
 '\nC. Stand-alone users.',
 '',
 '\nD. Casual end users.',
 'Answer: B',
 '62 Which database level is closest to the users?',
 'A. External',
 '',
 '\nB. Internal',
 '',
 '\nC. Physical',
 '',
 '\nD. Conceptual',
 'Answer: A',
 '63 Which are the two ways in which entities can participate in a relationship?',
 'A. Passive and active',
 '',
 '\nB. Total and partial',
 '',
 '\nC. Simple and Complex',
 '',
 '\nD. All of the above',
 'Answer: B',
 '64 The result of the UNION operation between R1 and R2 is a relation that includes',
 'A. all the tuples of R1',
 '',
 '\nB. all the tuples of R2',
 '',
 '\nC. all the tuples of R1 and R2',
 '',
 '\nD. all the tuples of R1 and R2 which have common columns',
 'Answer: D',
 '65 Which of the following is a comparison operator in SQL?',
 'A. =',
 '',
 '\nB. LIKE',
 '',
 '\nC. BETWEEN',
 '',
 '\nD. All of the above',
 'Answer: D',
 '66 A set of possible data values is called',
 'A. attribute.',
 '',
 '\nB. degree.',
 '',
 '\nC. tuple.',
 '',
 '\nD. domain.',
 'Answer: D',
 '67 Which of the operations constitute a basic set of operations for manipulating relational data?',
 'A. Predicate calculus',
 '',
 '\nB. Relational calculus',
 '',
 '\nC. Relational algebra',
 '',
 '\nD. None of the above',
 'Ans:C',
 '68 Which of the following is another name for the weak entity?',
 'A. Child',
 '',
 '\nB. Owner',
 '',
 '\nC. Dominant',
 '',
 '\nD. All of the above',
 'Answer: A',
 '69 Which of the following database object does not physically exist?',
 'A. base table',
 '',
 '\nB. index',
 '',
 '\nC. view',
 '',
 '\nD. none of the above',
 'Answer: C',
 '70 NULL is',
 'A. the same as 0 for integer',
 '',
 '\nB. the same as blank for character',
 '',
 '\nC. the same as 0 for integer and blank for character',
 '',
 '\nD. not a value',
 'Answer: D',
 '71 Which of the following is a record based logical model?',
 'A. Network Model',
 '',
 '\nB. Object-oriented model',
 '',
 '\nC. E-R Model',
 '',
 '\nD. None of these',
 'Answer: A',
 '72 A data dictionary is a special file that contains:',
 'A. The name of all fields in all files.',
 '',
 '\nB. The width of all fields in all files.',
 '',
 '\nC. The data type of all fields in all files.',
 '',
 '\nD. All of the above.',
 'Answer: D',
 '73 A file manipulation command that extracts some of the records from a file is called',
 'A. SELECT',
 '',
 '\nB. PROJECT',
 '',
 '\nC. JOIN',
 '',
 '\nD. PRODUCT',
 'Answer: A',
 '74 The physical location of a record is determined by a mathematical formula that transforms a file key into a record location is:',
 'A. B-Tree File',
 '',
 '\nB. Hashed File',
 '',
 '\nC. Indexed File',
 '',
 '\nD. Sequential file.',
 'Answer: B',
 '75 Using Relational Algebra the query that finds customers, who have a balance of over 1000 is',
 'A. P Customer_name (S balance >1000 (Deposit))',
 '',
 '\nB. S Customer_name (P balance >1000 (Deposit))',
 '',
 '\nC. P Customer_name (S balance >1000 (Borrow))',
 '',
 '\nD. S Customer_name (P balance >1000 (Borrow))',
 'Answer: A',
 '76 A primary key is combined with a foreign key creates',
 'A. Parent-Child relationship between the tables that connect them.',
 '',
 '\nB. Many to many relationships between the tables that connect them.',
 '',
 '\nC. Network model between the tables that connect them.',
 '',
 '\nD. None of the above.',
 'Answer: A',
 '77 In E-R Diagram derived attribute is represented by',
 'A. Ellipse',
 '',
 '\nB. Dashed ellipse',
 '',
 '\nC. Rectangle',
 '',
 '\nD. Triangle',
 'Answer: B',
 '78 Cross Product is a:',
 'A. Unary Operator',
 '',
 '\nB. Ternary Operator',
 '',
 '\nC. Binary Operator',
 '',
 '\nD. Not an operator',
 'Answer: C',
 '79 An instance of relational schema R (A, B, C) has distinct values of A, including NULL values. Which one of the following is true?',
 'A. A is a candidate key',
 '',
 '\nB. A is not a candidate key',
 '',
 '\nC. A is a Primary Key',
 '',
 '\nD. Both A. and C.',
 'Answer: B',
 '80 Consider the join of a relation R with relation S. If R has m tuples and S has n tuples, then the maximum size of join is:',
 'A. mn',
 '',
 '\nB. m+n',
 '',
 '\nC. (m+n)/2',
 '',
 '\nD. 2(m+n)',
 'Ans: A.',
 '81 The natural join is equal to:',
 'A. Cartesian Product',
 '',
 '\nB. Combination of Union and Cartesian product',
 '',
 '\nC. Combination of selection and Cartesian product',
 '',
 '\nD. Combination of projection and Cartesian product',
 'Answer: D',
 '82 Which one of the following is not true for a view:',
 'A. A view is derived from other tables.',
 '',
 '\nB. A view is a virtual table.',
 '',
 '\nC. A view definition is permanently stored as part of the database.',
 '',
 '\nD. The view never contains derived columns.',
 'Answer: C',
 '83 A primary key, if combined with a foreign key, creates',
 'A. Parent-Child relationship between the tables that connect them.',
 '',
 '\nB. Many to many relationships between the tables that connect them.',
 '',
 '\nC. Network model between the tables that connect them.',
 '',
 '\nD. None of the above.',
 'Answer: A',
 '84 In E-R Diagram relationship type is represented by',
 'A. Ellipse',
 '',
 '\nB. Dashed ellipse',
 '',
 '\nC. Rectangle',
 '',
 '\nD. Diamond',
 'Answer: D',
 '85 Hierarchical model is also called',
 'A. Tree structure',
 '',
 '\nB. Plex Structure',
 '',
 '\nC. Normalise Structure',
 '',
 '\nD. Table Structure',
 'Answer: A',
 '86 To delete a particular column in a relation the command used is:',
 'A. UPDATE',
 '',
 '\nB. DROP',
 '',
 '\nC. ALTER',
 '',
 '\nD. DELETE',
 'Answer: C',
 '87 The ______ operator is used to compare a value to a list of literals values that have been specified.',
 'A. BETWEEN',
 '',
 '\nB. ANY',
 '',
 '\nC. IN',
 '',
 '\nD. ALL',
 'Answer: A',
 '88 A logical schema',
 'A) is the entire database',
 '',
 '\nB) is a standard way of organising information into an accessible part',
 '',
 '\nC) describe how data is actually stored on disk',
 '',
 '\nD) None of these',
 'Answer: A',
 '89 A B-tree of order m has maximum of _____________ children',
 'A. m',
 '',
 '\nB. m+1',
 '',
 '\nC. m-1',
 '',
 '\nD. m/2',
 'Answer: A',
 '90 _____________ function divides one numeric expression by another and returns the remainder.',
 'A. POWER',
 '',
 '\nB. MOD',
 '',
 '\nC. ROUND',
 '',
 '\nD. REMAINDER',
 'Answer: B',
 '91 A data manipulation command the combines the records from one or more tables is called',
 'A. SELECT',
 '',
 '\nB. PROJECT',
 '',
 '\nC. JOIN',
 '',
 '\nD. PRODUCT',
 'Answer: C',
 '92 In E-R diagram generalisation is represented by',
 'A. Ellipse',
 '',
 '\nB. Dashed ellipse',
 '',
 '\nC. Rectangle',
 '',
 '\nD. Triangle',
 'Answer: D',
 '93 _________ is a virtual table that draws its data from the result of an SQL SELECT statement.',
 'A. View',
 '',
 '\nB. Synonym',
 '',
 '\nC. Sequence',
 '',
 '\nD. Transaction',
 'Answer: A',
 '94 The method of access which uses key transformation is known as',
 'A. Direct',
 '',
 '\nB. Hash',
 '',
 '\nC. Random',
 '',
 '\nD. Sequential',
 'Answer: B',
 '95 A table joined with itself is called',
 'A. Join',
 '',
 '\nB. Self Join',
 '',
 '\nC. Outer Join',
 '',
 '\nD. Equi Join',
 'Answer: B',
 '96 _________ data type can store unstructured data',
 'A. RAW',
 '',
 '\nB. CHAR',
 '',
 '\nC. NUMERIC',
 '',
 '\nD. VARCHAR',
 'Answer: A',
 '---- >> Related Posts of Above Questions :::']

In [112]:
#A = []
A = options[2::9]
B = options[4::9]
C = options[6::9]
D = options[8::9]

In [94]:
l_ans = [a.replace('Answer:', ' ') for a in ans]
l_ans = [a.replace('Ans:', ' ') for a in l_ans]
l_ans = [a.replace('\xa0', ' ') for a in l_ans]
print(l_ans)

['  A', '  B', '  A', '  B ', '  C', '  B', '  D', '  C', '  C', '  C', '  D', '  B', '  D', '  C', '  A', '  A', '  A', '  A', '  B', '  A.', '  B', '  D', '  A', '  B', '  D', '  B', '  C', '  B', '  C', '  A', '  C', '  A', '  B', '  C', '  D', '  C', '  B', '  B', '  D both B. and C.', '  A.', '  C', '  A', '  C', '  C', '  A', '  C', '  D', '  C', '  C', '  D', '  B', '  D', '  B', '  A', '  D', '  A', '  D', '  C', '  D', '  B', '  B', '  A', '  B', '  D', '  D', '  D', ' C', '  A', '  C', '  D', '  A', '  D', '  A', '  B', '  A', '  A', '  B', '  C', '  B', '  A.', '  D', '  C', '  A', '  D', '  A', '  C', '  A', '  A', '  A', '  B', '  C', '  D', '  A', '  B', '  B', '  A']

In [115]:
A_ans = [a.replace('\n', ' ') for a in A]
B_ans = [a.replace('\n', ' ') for a in B]
C_ans = [a.replace('\n', ' ') for a in C]
D_ans = [a.replace('\n', ' ') for a in D]

In [116]:
len(D_ans)

96

In [123]:
#formalising a dataframe 
#for i in range(1,len(df)):
df = pd.DataFrame({'question_text':qs,'question_type':1,'choice_A_text':A_ans,'choice_B_text':B_ans,'choice_C_text':C_ans,'choice_D_text':D_ans,'choice_E_text':' ','correct_choice':l_ans,
                   'correct_puzzle_answer':" ",'difficulty_level':1,'is_deleted':0}) 
df.insert(0, 'id', range(1, 1 + len(df)))
df.to_csv('DBMS_quiz.csv', index=False, encoding='utf-8')

In [124]:
df

,id,question_text,question_type,choice_A_text,choice_B_text,choice_C_text,choice_D_text,choice_E_text,correct_choice,correct_puzzle_answer,difficulty_level,is_deleted
0,1,"1. In the relational model, cardinality is ter...",1,A. A number of tuples.,B. A number of attributes.,C. A number of tables.,D. A number of constraints.,,A,,1,0
1,2,2. Relational calculus is a,1,A. Procedural language.,B. Non- Procedural language.,C. Data definition language.,D. High-level language.,,B,,1,0
2,3,3. The view of total database content is,1,A. Conceptual view.,B. Internal view.,C. External view.,D. Physical View.,,A,,1,0
3,4,4. Cartesian product in relational algebra is,1,A. a Unary operator.,B. a Binary operator.,C. a Ternary operator.,D. not defined.,,B,,1,0
4,5,5. DML is provided for,1,A. Description of the logical structure of a d...,B. The addition of new structures in the data...,C. Manipulation & processing of the database.,D. Definition of a physical structure of the ...,,C,,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
91,92,92 In E-R diagram generalisation is represente...,1,A. Ellipse,B. Dashed ellipse,C. Rectangle,D. Triangle,,D,,1,0
92,93,93 _________ is a virtual table that draws its...,1,A. View,B. Synonym,C. Sequence,D. Transaction,,A,,1,0
93,94,94 The method of access which uses key transfo...,1,A. Direct,B. Hash,C. Random,D. Sequential,,B,,1,0
94,95,95 A table joined with itself is called,1,A. Join,B. Self Join,C. Outer Join,D. Equi Join,,B,,1,0
95,96,96 _________ data type can store unstructured ...,1,A. RAW,B. CHAR,C. NUMERIC,D. VARCHAR,,A,,1,0